# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true

# Mod properties
mod.version=0.3.1
mod.group=com.github.zly2006
mod.id=x-backup
mod.name=X Backup

# for fabric.mod.json
mod.mc_dep=[VERSIONED]
# for release title
mod.mc_title=[VERSIONED]
# for release metadata
mod.mc_targets=[VERSIONED]

# Global dependencies
deps.kotlin_loader_version=1.12.3+kotlin.2.0.21
deps.exposed_version=0.53.0
deps.fabric_loader=0.16.9

# Versioned dependencies
deps.yarn_build=[VERSIONED]
deps.fabric_api=[VERSIONED]
